### ISSUE TITLE
Bug report: dqn_atari.py won't run, ValueError exception called

### ISSUE THREAD

**Issue by allengee** [matthiasplappert/keras-rl#24] opened 2016-09-22 06:12 UTC
allen:~/Tutorials/KerasRL/Doc$ python dqn_atari.py 
Using TensorFlow backend.
[2016-09-21 22:54:24,033] Making new env: Breakout-v0
Traceback (most recent call last):
  File "dqn_atari.py", line 70, in <module>
    model.add(Convolution2D(32, 8, 8, subsample=(4, 4), input_shape=(WINDOW_LENGTH,) + INPUT_SHAPE))
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/models.py", line 276, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 370, in create_input_layer
    self(x)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/layers/convolutional.py", line 466, in call
    filter_shape=self.W_shape)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1579, in conv2d
    x = tf.nn.conv2d(x, kernel, strides, padding=padding)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/common_shapes.py", line 246, in conv2d_shape
    padding)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/common_shapes.py", line 184, in get2d_conv_output_size
    (row_stride, col_stride), padding_type)
  File "/Users/Allen/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/common_shapes.py", line 149, in get_conv_output_size
    "Filter: %r Input: %r" % (filter_size, input_size))
ValueError: Filter must not be larger than the input: Filter: (8, 8) Input: (4, 84)

**Comment by matthiasplappert** [comment] 2016-09-22 16:59
Thanks for reporting this. The problem is related to the different ordering of dimensions for images in TensorFlow and Theano. This has been addressed in https://github.com/matthiasplappert/keras-rl/commit/897f101f4a2420d917c5b81d53fff11b210ae520 and should now work for both cases.

**Closed by matthiasplappert** 2016-09-22 16:59 UTC
